# Generated by Django 5.1 on 2024-09-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testproduct',
            name='created',
        ),
        migrations.RemoveField(
            model_name='testproduct',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='testproduct',
            name='updated',
        ),
        migrations.AlterField(
            model_name='testproduct',
            name='stock',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество на складе'),
        ),
    ]
