# Generated by Django 5.1 on 2024-10-04 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_testcategory_testproduct_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название бренда')),
                ('description', models.TextField(verbose_name='Описание бренда')),
                ('logo', models.ImageField(upload_to='logos/', verbose_name='Лого бренда')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ClothesSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20, verbose_name='Размер одежды')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название цвета')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Страна производитель')),
                ('flag', models.ImageField(upload_to='flags/', verbose_name='Флаг страны')),
            ],
            options={
                'verbose_name': 'Страна производитель',
                'verbose_name_plural': 'Страны производители',
            },
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название материала')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='ShoeSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EUSize', models.CharField(max_length=10, verbose_name='Европейский размер')),
                ('USSize', models.CharField(max_length=10, verbose_name='Американский размер')),
                ('CM', models.PositiveIntegerField(verbose_name='Сантиметр')),
            ],
            options={
                'verbose_name': 'Размер обуви',
                'verbose_name_plural': 'Размеры обуви',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название подкатегории')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='subcategories/', verbose_name='Фотография')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='product.category')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название обуви')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('unisex', 'unisex')], default='unisex')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='shoes/', verbose_name='Фотография')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.brand', verbose_name='Бренд')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.color', verbose_name='Цвет')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.country', verbose_name='Страна производитель')),
                ('fabric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.fabric', verbose_name='Материал')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.shoesize', verbose_name='Размер обуви')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoes', to='product.subcategory')),
            ],
            options={
                'verbose_name': 'Обувь',
                'verbose_name_plural': 'Обувь',
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название одежды')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('unisex', 'unisex')], default='unisex', verbose_name='Пол')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='clothes/', verbose_name='Фотография')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.brand', verbose_name='Бренд')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.clothessize', verbose_name='Размер')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.color', verbose_name='Цвет')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.country', verbose_name='Страна производитель')),
                ('fabric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.fabric', verbose_name='Материал')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to='product.subcategory')),
            ],
            options={
                'verbose_name': 'Одежда',
                'verbose_name_plural': 'Одежда',
            },
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название аксессуара')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('unisex', 'unisex')], default='unisex', verbose_name='Пол')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='accessories/', verbose_name='Фотография')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.brand', verbose_name='Бренд')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.color', verbose_name='Цвет')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.country', verbose_name='Страна производитель')),
                ('fabric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.fabric', verbose_name='Материал')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='product.subcategory')),
            ],
            options={
                'verbose_name': 'Аксессуар',
                'verbose_name_plural': 'Аксессуары',
                'ordering': ['title'],
            },
        ),
    ]
