# Generated by Django 5.1 on 2024-10-04 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_brand_category_clothessize_color_country_fabric_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothessize',
            options={'verbose_name': 'Размер одежды', 'verbose_name_plural': 'Размеры одежды'},
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Изображение')),
                ('accessory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessory_image', to='product.accessory', verbose_name='Фото аксессуара')),
                ('cloth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clothes_image', to='product.clothes', verbose_name='Фото одежды')),
                ('shoe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoes_image', to='product.shoes', verbose_name='Фото обуви')),
            ],
            options={
                'verbose_name': 'Изображение продукта',
                'verbose_name_plural': 'Изображения продуктов',
            },
        ),
    ]
