# Generated by Django 5.1 on 2024-10-04 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_clothessize_options_productimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accessories/', verbose_name='Изображение')),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_image', to='product.accessory', verbose_name='Фото аксессуара')),
            ],
            options={
                'verbose_name': 'Изображение акссесуара',
                'verbose_name_plural': 'Изображения акссесуаров',
            },
        ),
        migrations.CreateModel(
            name='ClothImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clothes/', verbose_name='Изображение')),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes_image', to='product.clothes', verbose_name='Фото одежды')),
            ],
            options={
                'verbose_name': 'Изображение одежды',
                'verbose_name_plural': 'Изображения одежды',
            },
        ),
        migrations.CreateModel(
            name='ShoeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shoes/', verbose_name='Изображение')),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoes_image', to='product.shoes', verbose_name='Фото обуви')),
            ],
            options={
                'verbose_name': 'Изображение обуви',
                'verbose_name_plural': 'Изображения обуви',
            },
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
